### ISSUE TITLE
[Feature idea] Custom org link type

### ISSUE THREAD

**Issue by josephmturner** [ahyatt/ekg#1]
Hello! Interesting project!

Have you considered adding a custom org link type for linking to ekg notes (or tag buffers)?

Joseph

**Comment by ahyatt** [comment]
I do have one, however it just links to tag buffers, and I want to make it link to individual notes.  But an org link that goes to `ekg:whatever`, will go to the `whatever` tag.  Org , `ekg:foo,bar` will go to a buffer that has either `foo` or `bar` tags.    I'll keep this open as a feature request to add what's missing: linking to an individual note.

**Comment by josephmturner** [comment]
Thank you for your response! I'm curious to follow this project going forward.
