### ISSUE TITLE
ekg-save-note: Symbol’s function definition is void: triples-with-transaction

### ISSUE THREAD

**Issue by gnusupport** [ahyatt/ekg#11]
It takes place in notes buffer, after `M-x ekg-capture` and after pressing `C-c C-c`

**Comment by ahyatt** [comment]
Can you check your version of `triples`?  It should be the one required by `ekg`, `0.2.3`.  You can see the function your instances says is missing does exist here: https://github.com/ahyatt/triples/blob/main/triples.el#L433

**Comment by gnusupport** [comment]
I have it, don't know, maybe it was not loaded. I can now see all functionality.
