### ISSUE TITLE
(wrong-type-argument ewoc nil)

### ISSUE THREAD

**Issue by gour** [ahyatt/ekg#115]
Hello,

I'm doing my first steps with ekg, and it is the best note-taking app I've encountered for quite some time...

After creating a note and adding few tags, I've tried to add URL as:

`Resource: https://some-url/`, but after saving the note I get:

```
Debugger entered--Lisp error: (wrong-type-argument ewoc nil)
  ewoc-nth(nil 0)
  ekg-edit-finalize()
  funcall-interactively(ekg-edit-finalize)
  command-execute(ekg-edit-finalize)
```

Any hint?

I'm using openSUSE Tumbleweed with GNU Emacs 29.1 (build 2, x86_64-suse-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0).

Sincerely,
Gour

**Comment by ahyatt** [comment]
You may have some malformed buffer for some reason, apparently a buffer that is `ekg-notes-mode` but has no `ekg-notes-ewoc`.  I haven't seen this before, but I checked in a change to the `develop` branch that should fix it, and will release a new version shortly.  Please re-open if you see this again, and thanks for the report!
