### ISSUE TITLE
Names of functions & structure

### ISSUE THREAD

**Issue by gnusupport** [ahyatt/ekg#12]
## Functions not intuitive, think of renaming

I see that naming of functions is not for me personally intuitive.

` M-x ekg-show-tag` is supposed to find notes, is it? 

I can't see how "show" is intuitive. To make it intuitive, I would understand better something like:

`ekg-show-notes-by-tag` 

## General structure comments

Comment on general structure, no, I can't agree, it is way too simple, and not enough structured. I understand the concept how you started designing it.

In your concept, you are using database power only slightly. As database is "organized, structured", I would propose that you use "structured" and "organized" a bit more.

Your database triples has been designed basically properly, but it is the only table. There is little to reference, little organized, you are giving yourself way too much work, as many things that are supposed to be handled by SQL database, you will need to handle by hand! 

For example, you are hard coding predicates, and user has no option to change it on high level, or add new predicates.

Imagine if predicates are in the table:

```
                                           Table "public.predicates"
┌────────────────────────┬─────────┬───────────┬──────────┬───────────────────────────────────────────────────┐
│         Column         │  Type   │ Collation │ Nullable │                      Default                      │
├────────────────────────┼─────────┼───────────┼──────────┼───────────────────────────────────────────────────┤
│ predicates_id          │ integer │           │ not null │ nextval('predicates_predicates_id_seq'::regclass) │
│ predicates_name        │ text    │           │          │                                                   │
│ predicates_description │ text    │           │          │                                                   │
└────────────────────────┴─────────┴───────────┴──────────┴───────────────────────────────────────────────────┘
Indexes:
    "predicates_pkey" PRIMARY KEY, btree (predicates_id)
    "predicates_index" UNIQUE, btree (predicates_name)
Referenced by:
    TABLE "oid2oid" CONSTRAINT "oid2oid_oid2oid_predicates_fkey" FOREIGN KEY (oid2oid_predicates) REFERENCES predicates(predicates_id)
    TABLE "semantictriplets" CONSTRAINT "semantictriplets_semantictriplets_predicates_fkey" FOREIGN KEY (semantictriplets_predicates) REFERENCES predicates(predicates_id)
```

And predicates shall start with those very rudimentary:

 1          is
 2          knows
 3          registered
etc.

Thus I am suggesting, and of course not at all protesting if not implemented, that things like predicates, objects, and subjects in semantic triplets get their own tables.

```
                                                               Table "public.semantictriplets"
┌──────────────────────────────────────────┬──────────────────────────┬───────────┬──────────┬───────────────────────────────────────────────────────────────┐
│                  Column                  │           Type           │ Collation │ Nullable │                            Default                            │
├──────────────────────────────────────────┼──────────────────────────┼───────────┼──────────┼───────────────────────────────────────────────────────────────┤
│ semantictriplets_id                      │ integer                  │           │ not null │ nextval('semantictriplets_semantictriplets_id_seq'::regclass) │
│ semantictriplets_datecreated             │ timestamp with time zone │           │ not null │ CURRENT_TIMESTAMP                                             │
│ semantictriplets_datemodified            │ timestamp with time zone │           │          │                                                               │
│ semantictriplets_usercreated             │ text                     │           │ not null │ CURRENT_USER                                                  │
│ semantictriplets_usermodified            │ text                     │           │ not null │ CURRENT_USER                                                  │
│ semantictriplets_subjecttriplet          │ integer                  │           │          │                                                               │
│ semantictriplets_subjecttable            │ text                     │           │          │                                                               │
│ semantictriplets_subjectcolumn           │ text                     │           │          │                                                               │
│ semantictriplets_subjectid               │ integer                  │           │          │                                                               │
│ semantictriplets_predicates              │ integer                  │           │ not null │                                                               │
│ semantictriplets_objecttriplet           │ integer                  │           │          │                                                               │
│ semantictriplets_objecttable             │ text                     │           │          │                                                               │
│ semantictriplets_objectcolumn            │ text                     │           │          │                                                               │
│ semantictriplets_objectid                │ integer                  │           │          │                                                               │
│ semantictriplets_description             │ text                     │           │          │                                                               │
│ semantictriplets_functiononsubjectcolumn │ text                     │           │          │                                                               │
│ semantictriplets_functiononobjectcolumn  │ text                     │           │          │                                                               │
└──────────────────────────────────────────┴──────────────────────────┴───────────┴──────────┴───────────────────────────────────────────────────────────────┘
Indexes:
    "semantictriplets_pkey" PRIMARY KEY, btree (semantictriplets_id)
    "semantictriplets_index" UNIQUE, btree (semantictriplets_subjecttable, semantictriplets_predicates, semantictriplets_objecttable)
Foreign-key constraints:
    "semantictriplets_semantictriplets_objecttriplet_fkey" FOREIGN KEY (semantictriplets_objecttriplet) REFERENCES semantictriplets(semantictriplets_id)
    "semantictriplets_semantictriplets_predicates_fkey" FOREIGN KEY (semantictriplets_predicates) REFERENCES predicates(predicates_id)
    "semantictriplets_semantictriplets_subjecttriplet_fkey" FOREIGN KEY (semantictriplets_subjecttriplet) REFERENCES semantictriplets(semantictriplets_id)
Referenced by:
    TABLE "semantictriplets" CONSTRAINT "semantictriplets_semantictriplets_objecttriplet_fkey" FOREIGN KEY (semantictriplets_objecttriplet) REFERENCES semantictriplets(semantictriplets_id)
    TABLE "semantictriplets" CONSTRAINT "semantictriplets_semantictriplets_subjecttriplet_fkey" FOREIGN KEY (semantictriplets_subjecttriplet) REFERENCES semantictriplets(semantictriplets_id)
Triggers:
    insert_username_semantictriplets BEFORE INSERT OR UPDATE ON semantictriplets FOR EACH ROW EXECUTE FUNCTION insert_username('semantictriplets_usermodified')
    semantictriplets_moddatetime BEFORE UPDATE ON semantictriplets FOR EACH ROW EXECUTE FUNCTION moddatetime('semantictriplets_datemodified')

```

As you can see each entry would have it's `date created` and `date modified` and that alone helps you with dates. Multiple users may collaborate and access the database. That is matter of the type of database.

In this particular design, which good purpose is brainstorming, subject is referencing the table, and ID, it can also reference triplet itself, and that means any other tables in the database may be placed in the semantic triplets table. Object is referencing other table or triplet, with the ID number.

### Entry example

Here is very practical example of the entry:

```
                             ID   1
                   Date created   "2022-07-06 19:44:02.244679+03"
                  Date modified   "2022-07-06 20:00:08.638015+03"
                   User created   "maddox"
                  User modified   "maddox"
                Subject triplet   nil
                  Subject table   "people"
                 Subject column   "people_id"
                     Subject ID   316178
                     Predicates   "registered"
                 Object triplet   nil
                   Object table   "commlines"
                  Object column   "commlines_value"
                      Object ID   29936
                    Description   "James registered this Lycamobile SIM card."
     Function on subject column   "get_full_contacts_name"
      Function on object column   nil
```

Subject is table `people` with column `people_id` and ID 316178, which is "James", there is date created, modified, user, predicate is "registered" and there is table `commlines` with `commlines_value` as subject, the real commline value is phone number, but such need not be specified in the database. The ID for phone number is 29936, there is description, and PostgreSQL (could be Emacs) function to run on columns. As some columns shall be represented in different ways. 

Then the object would be represented as:

James registered phone number +256726295314 belonging to Lyca Mobile

Words "phone number" and "belonging to Lyca Mobile" would be constructed by function. as "Lyca" is related to phone, it is not necessarily in the triplet.

Otherwise basic meaning would be:

"James registered commlines_value +256726295314"

I am well aware that everything could be put in semantic triplets. All the database could be placed inside. But that way of doing require liberation of user for user to decide what is subject, predicate, object.

### Teaching triplets

Then you build it, you teach it:

1. person "has" notes
2. person has name
3. note has date
4. note has text
5. tag has date
6. note has Emacs mode
7. org-mode is Emacs mode
8. text-mode is Emacs mode
9. James is person
10. James registered note (note ID is 10)
11. note (10) has text (ID is 11)
12. text (11) is "My text here"

The last 2 above must reference to ID of the triplet like 10, 11. 

It is totally possible to have all database based on triplets as foundation.

But with SQL databases, I find that mixture is better. 

Personally, I am only brainstorming on that, I did not go implementing
it. But that approach shall leave to user how to define triplets.

If database is generic, then application shall exist which is very
generic, and which allows user to build the new application, by
defining it in triplets.

### Reference

I recommend reviewing:

OneModel - Record, manage and share any knowledge:  
http://onemodel.org/1/e-9223372036854618119.html

That may be the best implementation of semantic triplets in software. I do not know others.

I am aware when it becomes so "basic" that people get confused.

Maybe some basic predicates and objects and subjects, shall be prepared for people.

I see predicates in `ekg` like:

- tagged/tag
- base/type
- time-tracked/creation-time

and I find those predicates way too high level, if there are no fundamental predicates, "is", "has".

Then I see triplet like:

`time-tracked/creation-time	base/unique	t`

or like

`33077773945	time-tracked/modified-time	1674284938`

or like

`33077805874	text/text	#("OK fine, my note is here." 0 25 (fontified t))`

So yes, you are using triplet database, but in different way how I
would expect it, more high level, and with mixture of a lot of text
instead of relations.

I believe that it is not scalable to keep everything in one database,
as then PostgreSQL or SQLite features can't be efficiently used.

## Different uses of triplets in relational databases

So there are for now 3 discovered types of usage of triplets:

1. the mixture of maximized freedom of using text, minimized database
   structure, which is represented by `ekg', without basic predicates
  
2. there is *One Model* example which asks to define basic predicates
   to teach the database, structuring more the objects, subjects,
   predicates;

3. there is my model where table `triplets` references other table,
   column, by their ID, with predicate to other table column. This
   becomes universal "key" among all tables in the database, showing
   relations that may not be otherwise defined.
   
## Universal UUID triplet table

And I also have more universal model that goes beyond. It is UUID to
UUID semantic triplets table:

```
                                    Table "public.uuid2uuid"
┌─────────────────────────┬──────────────────────────┬───────────┬──────────┬───────────────────┐
│         Column          │           Type           │ Collation │ Nullable │      Default      │
├─────────────────────────┼──────────────────────────┼───────────┼──────────┼───────────────────┤
│ uuid2uuid_uuid          │ uuid                     │           │ not null │ gen_random_uuid() │
│ uuid2uuid_datecreated   │ timestamp with time zone │           │ not null │ CURRENT_TIMESTAMP │
│ uuid2uuid_datemodified  │ timestamp with time zone │           │          │                   │
│ uuid2uuid_usercreated   │ text                     │           │ not null │ CURRENT_USER      │
│ uuid2uuid_usermodified  │ text                     │           │ not null │ CURRENT_USER      │
│ uuid2uuid_uuidobject    │ uuid                     │           │ not null │                   │
│ uuid2uuid_uuidpredicate │ uuid                     │           │ not null │                   │
│ uuid2uuid_uuidsubject   │ uuid                     │           │ not null │                   │
│ uuid2uuid_description   │ text                     │           │          │                   │
└─────────────────────────┴──────────────────────────┴───────────┴──────────┴───────────────────┘
Indexes:
    "uuid2uuid_pkey" PRIMARY KEY, btree (uuid2uuid_uuid)
```

### Requirement by UUID triplet table

- Objects must have their UUID

- If objects do no have their UUID, they can be recorded to get the UUID

- Remote UUID may be recorded to have local UUID, which can then
  specify what is that remote UUID

- Example is recording https://www.example.com as URL in database with
  the UUID: 0488c0f0-139a-4173-853d-cdba68b4fa65
  
- There must be functions to find UUID and their representation

- Even the UUID predicate is referenced by UUID

- Referencing depends of program function, not of database modelling

- Adding packages and extensions providing UUID's is easy, it becomes
  possible to go acress types of databases
  
- I recommend table design such as: "TABLENAME_uuid", as that way it
  becomes easy to fetch list of tables and find their UUID column!

#### People

1. Create `people` table
2. Assign UUID to each entry
3. James has UUID 6b6ea318-dda4-473f-9dcd-f3d79074f569

#### Notes

1. Create `notes` table
2. Assign UUID to each entry

#### Create note about James

1. Program asks what is note about? People? Which one? James
   6b6ea318-dda4-473f-9dcd-f3d79074f569 That becomes subject
   
2. Predicate is "has", but "has" also has UUID
   (21057255-79fe-44ae-bd52-26df3c56ac8d), it could came from any of
   tables, not only `predicates`!

3. Note is created with UUID 144bc138-6470-49f8-8d65-37dd00bd6f6d, it
   becomes subject.

4. New entry is also recorded in uuid2uuid triplets table that:

   UUID subject: 6b6ea318-dda4-473f-9dcd-f3d79074f569 (James)
   with 
   UUID predicate: 21057255-79fe-44ae-bd52-26df3c56ac8d (has)
   with
   UUID object: 144bc138-6470-49f8-8d65-37dd00bd6f6d
   
#### User wants some tags?

1. Create table tags, each get assigned UUID

then follow various workflows:

1. Find all notes about James, there are 433

2. Narrow to those 12 which are related to "mining" (their names need not reflect that word)

3. Tag with "mining" cefd72ef-b9d7-4ea8-8c5f-d405443d254e

**Note subject** 144bc138-6470-49f8-8d65-37dd00bd6f6d
**has** 21057255-79fe-44ae-bd52-26df3c56ac8d
cefd72ef-b9d7-4ea8-8c5f-d405443d254e

Then it becomes possible to tag anything and anything without having
particular database structure.

#### User wants some properties?

Some workflow as above. Even all of properties and tags are just
different name for classification, so everything could be stored in
the triplets table with subject few other tables: `subjects`,
`predicates` and `objects`, where each such table could be something
like:

```
-- ------------------------------------------
-- ------------ Table subjects
-- ------------------------------------------
DROP SEQUENCE subjects_id_seq;

CREATE TABLE subjects (
subjects_id SERIAL NOT NULL PRIMARY KEY,
subjects_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
subjects_datecreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
subjects_datemodified TIMESTAMP,
subjects_usercreated TEXT NOT NULL DEFAULT current_user,
subjects_usermodified TEXT NOT NULL DEFAULT current_user,
subjects_name TEXT NOT NULL,
subjects_description TEXT
subjects_representation TEXT,
subjects_otheruuid UUID
);

-- Triggers
-- For Date Modified
CREATE TRIGGER subjects_moddatetime
BEFORE UPDATE ON subjects
FOR EACH ROW
EXECUTE PROCEDURE moddatetime(subjects_datemodified);

-- For User Modified
CREATE TRIGGER insert_username_subjects
BEFORE INSERT OR UPDATE ON subjects
FOR EACH ROW
EXECUTE PROCEDURE insert_username(subjects_usermodified);
```

So 4 tables could do the work:

- subjects
- predicats
- objects
- triplets 

and instead of triplets referencing primary keys, they can reference
UUID to allow full liberation from database, and allow extensibility.

Tables like `subjects` and `objects` can have their textual
representation of names. This representation need not go into
`triplets` table.

The above structure I find more suitable for generic smart database design.

**Comment by gnusupport** [comment]
I have been playing with lower level visual interface in Emacs to edit semantic triplets and then I realized that table such as `subjects` or `objects` could be unified into one as "human" as subject may as well be "object".

**Comment by gnusupport** [comment]
After few hours, here is the interface, and you should have this interface for triplets:

[![https://gnu.support/images/2023/01/2023-01-21/mpv-shot0002.jpg](https://gnu.support/images/2023/01/2023-01-21/mpv-shot0002.jpg)](https://gnu.support/images/2023/01/2023-01-21/2023-01-21-13:16:29.ogv)

Video link: https://gnu.support/images/2023/01/2023-01-21/2023-01-21-18:03:23.ogv

I can send you that as package, when it becomes finished. Or give you functions right away.

I hope you understand that user of any triplets would need integrated way to create objects and subjects, which I call now _"sobjects"_, which can then be associated to predicates, and then triplets associated to triplets when necessary.

Then any user of such system could visually define relationships, and questions, and then program could parse triplets and generate the application automatically, like questioning or input of data to computer, converting that data, and representing it or sharing, etc. At least basic functions could be possible with it.

Then you will get e-mail through I have sent to mailing list to understand better what I mean.

**Comment by ahyatt** [comment]
Thank you, as usual I think this is very interesting and nice feedback.

However, as a specific issue, there's too much here for one actual Github issue which could plausibly be dealt with.  So let me take your very concrete point at the top of your comment as the issue: the function names we expose could be better.  This is a valid complaint, and I'll see what I can do to fix it.

For your suggestions about the structure, let's continue that discussion via the email you already have sent.  I don't think it has a lot to do with this project.  It does have a lot to do with the `triples` package, and in essence most of what you are talking about is asking for a re-implementation of that, which will produce a fuller set of functionality.  This project is really an application built on triples, it isn't really about giving the user access to the lower-level RDF concepts.  As it evolves, I think the concepts you mention may help resolve design issues, but I'd prefer to let the functionality be the driving principle here.
