### ISSUE TITLE
can't create org-header at top of capture note

### ISSUE THREAD

**Issue by vigilancetech-com** [ahyatt/ekg#121]
I open a new note with ekg-capture.   I'm in doom emacs with evil mode.  I can't do 'a' 'o' or 'i' to enter insert mode and then do alt-enter to create a new header because it says the buffer is read only.  I can't even put in a space char and then hit alt-enter.   I actually have to type a visible character before I can hit alt-enter and get a '*'

I can however hit the '*' for the visible character, so it's not the end of the world.  Just an annoying inconsistency. 

I plan on using ekg a **lot** with attachments, but that requires a header to attach the files to (from my research, see the Discussions board).

**Comment by ahyatt** [comment]
I'll look into this, but due to the weird things I'm doing with the metadata section, org mode often gets fairly confused.  I think I've looked into this before and was unable to find a solution, but let me look again.

**Comment by ahyatt** [comment]
I believe I've fixed the problem now.  Please take a look and let me know how it works for you.
