### ISSUE TITLE
low contrast face on tags in note edit mode

### ISSUE THREAD

**Issue by vigilancetech-com** [ahyatt/ekg#123]
I'm running the doom-homage-black theme and when I go to edit a note the background of the tags field is white with the lettering light yellow (so their content is constructively invisible).

For instance, here's a screenshot:

![image](https://github.com/ahyatt/ekg/assets/20651234/db11463b-f023-49bf-9038-72f66fe717e6)

**Comment by ahyatt** [comment]
Thanks for the report, this will be fixed with the next release!
