### ISSUE TITLE
ekg-org-roam and MELPA recipe(s)?

### ISSUE THREAD

**Issue by bdarcus** [ahyatt/ekg#14]
Currently, the MELPA recipe doesn't install `ekg-org-roam.el`; only `ekg.el`. That makes sense if you intend to add a separate MELPA recipe, but maybe not otherwise?

**Comment by ahyatt** [comment]
`ekg-org-roam` is now included, thanks to https://github.com/melpa/melpa/pull/8399.

**Comment by ahyatt** [comment]
With commit https://github.com/ahyatt/ekg/commit/7a112094e34ad54406e028e83afcff90ccab143f, we've changed the README to have instructions compatible with the fact that `ekg-org-roam` is part of the `ekg` package on MELPA now.
