### ISSUE TITLE
Why no Sponsor option?

### ISSUE THREAD

**Issue by VernonGrant** [ahyatt/ekg#163]
Hi, 

I use your note taking package on a daily basis and it has become a fundamental part of my daily workflow. I would like to givea couple dollars to this project every month to support its continued development and maintenance. Would you consider adding Github sponsors?

**Comment by ahyatt** [comment]
Thanks for suggesting this!  I'm super happy you are enjoying ekg, and I'll add a sponsor button for anyone who wants to throw a bit of money my way.
