### ISSUE TITLE
ekg-email.el

### ISSUE THREAD

**Issue by peterjauhal** [ahyatt/ekg#177]
Hello Andrew
Just watched your fantastic video. Love the new functionality. I tried to install it. Unfortunately I run into the error: "wrong type argument: stringp, nil". 
please advise. I am not a programmer so I have probably made some basic error.
I would love to get it working as I think I would use it all the time to query my emails.
Many thanks
Peter

**Comment by ahyatt** [comment]
Should be fixed now, please try again and let me know how it works for you.

**Comment by peterjauhal** [comment]
Still receiving the same error Andrew. Maybe because i am on Arch Linux?

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=cGV0ZXJqYXVoYWxAZ21haWwuY29t>

**Comment by ahyatt** [comment]
Did you re-evaluate the `ekg-email.el` buffer before trying again?  If so, can you run `M-x toggle-debug-on-error` and add a complete backtrace?

**Comment by peterjauhal** [comment]
Could you please advise on the next steps?

Thanks,
Peter

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=cGV0ZXJqYXVoYWxAZ21haWwuY29t>

**Comment by ahyatt** [comment]
@peterjauhal did you see my previous comment (https://github.com/ahyatt/ekg/issues/177#issuecomment-2325582783)?  Let me know if you have any questions about it, please.

**Comment by peterjauhal** [comment]
yes i copied your new code into my custom.el and reevaluated and received no errors. I then restarted my Emacs and tried gnus and copying an email into ekg and received the following debug message:
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("," nil 0)
  split-string(nil ",")
  (mapcar #'string-trim (split-string (gnus-fetch-field "To") ","))
  (let* ((to (mapcar #'string-trim (split-string (gnus-fetch-field "To") ","))) (from (gnus-fetch-field "From")) (cc (let* ((cc (and t (gnus-fetch-field "Cc")))) (if cc (mapcar #'string-trim (split-string cc ",")) nil))) (subject (gnus-fetch-field "Subject")) (prop-plist (list ':email/to to ':email/from from ':titled/title subject))) (if cc (progn (plist-put prop-plist :email/cc cc))) (ekg-capture :text (gnus-with-article-buffer (buffer-substring-no-properties (save-excursion (article-goto-body) (point)) (point-max))) :properties prop-plist))
  ekg-email-from-gnus()
  funcall-interactively(ekg-email-from-gnus)
  call-interactively(ekg-email-from-gnus record nil)
  command-execute(ekg-email-from-gnus record)
  execute-extended-command(nil "ekg-email-from-gnus" nil)
  funcall-interactively(execute-extended-command nil "ekg-email-from-gnus" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

please let me know what I am doing wrong.
Peter

**Comment by ahyatt** [comment]
Hm, it seems like `(gnus-fetch-field "To")` is returning `nil`.  You wouldn't be able to shown `ekg-email-from-gnus` in the command picker if you weren't in an Gnus article (`gnus-article-mode`).  But if you were, `(gnus-fetch-field "To")` should work.  Every email should have that field.  It's hard to say more without knowing your setup for gnus and if anything weird is going on where you are running it.

So, just to check, you are running it from a mail shown as a Gnus article?  And I imagine there's nothing weird about this mail?  

You can also try running `(gnus-fetch-field "To")` manually, via `eval-expression` to confirm that it really is returning `nil` from the article.  Sorry I can't help more precisely, I don't know much about gnus internals.

**Comment by peterjauhal** [comment]
Unfortunately, it didn't work, and the fetch-field command still returns nothing. Could you please share your gnus configuration files? I hope copying them might resolve the issue.

Thanks,
Peter

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=cGV0ZXJqYXVoYWxAZ21haWwuY29t>

**Comment by peterjauhal** [comment]
Hi Andrew,

Thanks for your help. It seems I don't have a .gnus.el file, so I created one with the following configuration:

(setq user-mail-address ***@***.*** <https://app.shortwave.com/s/group%3Ayour-email%40example.com>" user-full-name "Your Name" smtpmail-smtp-server "smtp.example.com <http://smtp.example.com>" send-mail-function 'smtpmail-send-it smtpmail-smtp-service 587)

Unfortunately, it didn't work, and the fetch-field command still returns nothing. Could you please share your gnus configuration files? I hope copying them might resolve the issue.

Thanks,
Peter

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=cGV0ZXJqYXVoYWxAZ21haWwuY29t>

**Comment by peterjauhal** [comment]
Hello Andrew,

It works with Elfeed as well—so cool! I'm trying to find a way to use ekg to interrogate my tasks.org <http://tasks.org> file but haven't succeeded yet. Could you please share how you handle your task list within ekg? I'd like to be able to use the llm to query my task list. If you use another task manager, I'd be interested in learning about that too. I currently use org-mode with the agenda function.

Thanks,
Peter

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=cGV0ZXJqYXVoYWxAZ21haWwuY29t>

**Comment by ahyatt** [comment]
When you say it works with Elfeed, I'm surprised.  What works exactly?  Elfeed isn't mail, so I wouldn't expect the mail functions in `ekg-email-from-gnus` to work.  And since it uses `gnus` specifically, I'm also surprised that `notmuch` would work.  Do you really get EKG notes with the to, from, etc. fields?

For gnus, i'm using the following simple configuration:

```emacs-lisp
(require 'gnus)

(setq gnus-select-method '(nnimap "gmail"
                                  (nnimap-address "imap.gmail.com")
                                  (nnimap-server-port "imaps")
                                  (nnimap-stream ssl)
                                  (nnmail-expiry-target "nnimap+gmail:[Gmail]/Trash")  ; Move expired messages to Gmail's trash.
                                  (nnmail-expiry-wait immediate))) ; Mails marked as expired can be processed immediately.

(setq smtpmail-smtp-server "smtp.gmail.com"
      smtpmail-smtp-service 587
      gnus-agent-queue-mail nil
      gnus-ignored-newsgroups "^to\\.\\|^[0-9. ]+\\( \\|$\\)\\|^[\"]\"[#'()]")
```

There's more to it than that, though, you have to set up your `.authinfo.gpg` and an application specific password from Google, but there are resources online on how to do that.

As for org tasks, I haven't integrated anything yet, but I'd like to.

**Comment by peterjauhal** [comment]
Thanks, Andrew. I asked the LLM to adjust your code for Notmuch and Elfeed, and it worked! With Elfeed, clicking on the article link saves the entire article in EKG, which is amazing. I also tried to get the LLM to create a to-do list manager in EKG, but it couldn't come up with anything functional. I am happy to send you the code the LLM produced if you want to look at it.

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=cGV0ZXJqYXVoYWxAZ21haWwuY29t>

**Comment by ahyatt** [comment]
Ah, I see, yes, that makes sense.  If you'd like to contribute your code for Notmuch to the `ekg-email` contrib, that would be appreciated, so please send a pull request.

**Comment by peterjauhal** [comment]
Hello Andrew
My code is below. I do not know anything about programming or github and so please feel free to use it as you see fit.
Best Regards,
Peter

;;; Code:

(require 'ekg)
(require 'triples)
(require 'seq)
(require 'notmuch)
(require 'gnus)
(require 'elfeed)

(defun ekg-email-add-schema ()
"Add the email schema to the ekg database."
(triples-add-schema ekg-db 'email
'(to :base/type string)
'(from :base/type string :base/unique t)
'(cc :base/type string))
(triples-add-schema ekg-db 'email-address
'(emails-to :base/virtual-reversed email/to)
'(emails-from :base/virtual-reversed email/from)
'(emails-cc :base/virtual-reversed email/cc))
(triples-add-schema ekg-db 'feed-entry
'(title :base/type string)
'(link :base/type string :base/unique t)
'(author :base/type string)
'(content :base/type string)))

;; Add the email schema to the database now, since the ekg-add-schema-hook is
;; not always run at the right time.
(when ekg-db
(ekg-email-add-schema))
(add-hook 'ekg-add-schema-hook 'ekg-email-add-schema)

(add-to-list 'ekg-metadata-parsers
(cons "Email-To" 'ekg-email--metadata-update-to))
(add-to-list 'ekg-metadata-parsers
(cons "Email-From" 'ekg-email--metadata-update-from))
(add-to-list 'ekg-metadata-parsers
(cons "Email-CC" 'ekg-email--metadata-update-cc))

(add-to-list 'ekg-property-multivalue-type (cons "Email-To" 'comma))
(add-to-list 'ekg-property-multivalue-type (cons "Email-CC" 'comma))

(add-to-list 'ekg-metadata-labels (cons :email/to "Email-To"))
(add-to-list 'ekg-metadata-labels (cons :email/from "Email-From"))
(add-to-list 'ekg-metadata-labels (cons :email/cc "Email-CC"))

(defun ekg-email--metadata-update-to (val)
"Update the email-to metadata with VAL."
(setf (ekg-note-properties ekg-note)
(plist-put (ekg-note-properties ekg-note) :email/to val)))

(defun ekg-email--metadata-update-from (val)
"Update the email-from metadata with VAL."
(setf (ekg-note-properties ekg-note)
(plist-put (ekg-note-properties ekg-note) :email/from val)))

(defun ekg-email--metadata-update-cc (val)
"Update the email-cc metadata with VAL."
(setf (ekg-note-properties ekg-note)
(plist-put (ekg-note-properties ekg-note) :email/cc val)))

(defun ekg-display-note-email (note)
"Display the email NOTE."
(let ((to (plist-get (ekg-note-properties note) :email/to))
(from (plist-get (ekg-note-properties note) :email/from))
(cc (plist-get (ekg-note-properties note) :email/cc)))
(if (or to from cc)
(concat "To: " (string-join to ", ") "\n"
"From: " from "\n"
"CC: " (string-join cc ", ") "\n"))))

(defun ekg-email-from-gnus ()
"Create a note with the current email as content and metadata."
(interactive nil gnus-article-mode)
(let* ((to (mapcar #'string-trim (split-string (gnus-fetch-field "To") ",")))
(from (gnus-fetch-field "From"))
(cc (when-let ((cc (gnus-fetch-field "Cc")))
(mapcar #'string-trim (split-string cc ","))))
(subject (gnus-fetch-field "Subject"))
(prop-plist `(:email/to ,to :email/from ,from :titled/title ,subject)))
(when cc
(plist-put prop-plist :email/cc cc))
(ekg-capture
:text (gnus-with-article-buffer
(buffer-substring-no-properties
(save-excursion
(article-goto-body)
(point))
(point-max)))
:properties prop-plist)))

(defun ekg-email-from-notmuch ()
"Create a note with the current email as content and metadata."
(interactive)
(let* ((to (or (notmuch-show-get-header "To") ""))
(from (or (notmuch-show-get-header "From") ""))
(cc (notmuch-show-get-header "Cc"))
(subject (notmuch-show-get-header "Subject"))
(prop-plist `(:email/to ,(if (not (string= to "")) (split-string to ",[ ]*") '())
:email/from ,from
:titled/title ,subject)))
(when cc
(plist-put prop-plist :email/cc (split-string cc ",[ ]*")))
(notmuch-show-view-all-mime-parts)
(ekg-capture
:text (buffer-string)
:properties prop-plist)))

(require 'shr) ;; Import the shr package

(defun ekg-feed-from-elfeed ()
"Create a note with the current Elfeed entry as content and metadata."
(interactive)
(let* ((entry (elfeed-search-selected :single)))
(if (not entry)
(error "No Elfeed entry selected. Please select an entry first.")
(let* ((title (elfeed-entry-title entry))
(link (elfeed-entry-link entry))
(author (elfeed-meta entry :author))
(content (elfeed-deref (elfeed-entry-content entry)))
(plain-text-content
(with-temp-buffer
(insert content)
(shr-render-region (point-min) (point-max))
(buffer-string)))
(prop-plist `(:feed-entry/title ,title
:feed-entry/link ,link
:feed-entry/author ,author)))
(ekg-capture
:text plain-text-content
:properties prop-plist)))))

(defun ekg-email-save (note)
"On a save, for any email addresses, type them with email-address.

NOTE is the note being saved."
(dolist (addr (seq-uniq
(delq nil
(append
(plist-get (ekg-note-properties note) :email/to)
(list (plist-get (ekg-note-properties note) :email/from))
(plist-get (ekg-note-properties note) :email/cc)))))
(when (and addr (stringp addr) (not (string= addr "")))
(triples-set-type ekg-db addr 'email-address))))

(add-hook 'ekg-note-save-hook #'ekg-email-save)

(defun ekg-email-delete (note-id)
"Delete email information associated with a note being deleted.

NOTE-ID is the id of the note that will be deleted."
(triples-remove-type ekg-db note-id 'email))

(add-hook 'ekg-note-delete-hook #'ekg-email-delete)

(defun ekg-email-addresses ()
"Return all addresses found in email."
(ekg-connect)
(seq-difference
(triples-subjects-of-type ekg-db 'email-address)
(ekg-inactive-note-ids)))

(defun ekg-email-get-notes-ids-with-address (addr)
"Get all notes ids with emails to/from/cc containing ADDR.

ADDR must be a value matching a stored address, and not, say just
an email address that is part of what we store in the triples."
(ekg-connect)
(seq-uniq
(let ((addr-vals (triples-get-type ekg-db addr 'email-address)))
(append
(plist-get addr-vals :emails-to)
(plist-get addr-vals :emails-from)
(plist-get addr-vals :emails-cc)))))

(defun ekg-email-show-notes-with-address (addr)
"Show all notes to, from, or cc'd to ADDR."
(interactive (list (completing-read "Addrs: "
(ekg-email-addresses))))
(ekg-connect)
(ekg-setup-notes-buffer
(format "with address: %s" addr)
(lambda () (sort
(mapcar #'ekg-get-note-with-id
(seq-filter
#'ekg-active-id-p
(ekg-email-get-notes-ids-with-address addr)))
#'ekg-sort-by-creation-time))
nil))

(provide 'ekg-email)
;;; ekg-email.el ends here
(custom-set-faces
;; custom-set-faces was added by Custom.
;; If you edit it by hand, you could mess it up, so be careful.
;; Your init file should contain only one such instance.
;; If there is more than one, they won't work right.
)

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=cGV0ZXJqYXVoYWxAZ21haWwuY29t>
