### ISSUE TITLE
defvar-keymap error

### ISSUE THREAD

**Issue by DarkBuffalo** [ahyatt/ekg#2]
Hi,
I just discovered this package with emacs conf and I find it great.

But when I install it here is the error that appears
`Symbol's function definition is void: defvar-keymap`

Config:
Emacs 28.2
Archlinux

**Comment by ahyatt** [comment]
Good find, this was introduced in emacs 29.  I'll see if I can find a way to do this that is a bit more backward compatible.

**Comment by DarkBuffalo** [comment]
Thanks @ahyatt 
now when I validate a note it displays the following error:
`triples-db-insert: Symbol’s function definition is void: plistp`

**Comment by ahyatt** [comment]
Hm, you don't have `plistp` in emacs 28's `subr.el`?  The help for this function doesn't mention that this was new in emacs 29.  I'll look into how to work around this today.

**Comment by ahyatt** [comment]
Other issues such as https://github.com/dengste/org-caldav/issues/189 seem to indicate that this is present in emacs for a while.  Can you please double-check `subr.el`?

**Comment by DarkBuffalo** [comment]
I think it's for emacs 29
https://github.com/emacs-mirror/emacs/commit/dedd19a2f5cbf16c8ac8a122b0c39ee4e178b9e8

**Comment by ahyatt** [comment]
Thanks, can you open another bug for this, then?  Also also please open a bug in the `triples` package, which also uses this same function.
