### ISSUE TITLE
Is it possible to export notes to other file formats?

### ISSUE THREAD

**Issue by anthrolisp** [ahyatt/ekg#27]
Is it possible to export notes from database to other file formats, such as ord or md?

**Comment by ahyatt** [comment]
Notes can be org, md, txt, but we don't support taking notes in one format and converting it to another one.  It should be doable if someone wants to add that capability and there's some library we can use to convert to org from md, but it seems like fringe functionality at the moment. What use-case did you have in mind?

**Comment by anthrolisp** [comment]
In the event that one no longer decides to use ekg, simply wanting to migrate the "notes" to plain text files.

**Comment by ahyatt** [comment]
Yes, that's coming.  But that isn't conversion of formats, that's just moving things from the database to a filesystem, maintaining the format.  You can check out a version in the logseq branch, where we now support export to logseq.  This will likely be merged into the next version of ekg.  Export to other things can be supported, but the question is what would be most useful.  If you would like to discuss these kinds of use-cases, maybe open a thread in the discussion forum.  Thanks for the question!
