### ISSUE TITLE
Renaming the tag/adding a tag to the current new note

### ISSUE THREAD

**Issue by alecStewart1** [ahyatt/ekg#33]
Hello!

This is my first dive into this kind of note taking in Emacs and I find this way to organizing notes to be very interesting.

Starting off, I'm not quite sure about manipulating the tag(s) of a new note. So `C-c e` is what I've bound `ekg-capture` to. A new note buffer opens and I go to the top where `Tags:` under the note properties are. I change it to something like `ekg`. I write the note, `C-c C-c` to save it. I run `M-x ekg-show-notes-with-tag`, there are no notes with the tag `ekg` only with the `date/[today's-date]`. I can obviously open that note and change the tag with `ekg-rename-tag`, but I shouldn't have to do that.

I start a new note, I want the tag be `work/some_project_im_on`. I try `ekg-rename-tag` in that new note buffer, set it to the new tag, add the note and save. `M-x ekg-show-notes-with-tag` and there's no note with the tag `work/some_project_im_on`.

Maybe there's a step I'm missing but I assumed the first attempt is what you're supposed to do and from the [manual](https://github.com/ahyatt/ekg/blob/develop/doc/ekg.org#61-note-properties) I think I'm not wrong in my assumption.

Thanks, and have a great day!

**Comment by alecStewart1** [comment]
Ah, I see. So if I start at the end of the line and hit `Backspace/Delete` to remove the default tag and the line is no longer highlighted (with `doom-nord` it's gray for me), ekg has no idea what the note property is anymore and thus won't change the tag(s).

I think maybe there should be a way, via interactive command or just a function bound to a key, to make it easy to change the tag(s). Or maybe there is and I just missed it.

**Comment by ahyatt** [comment]
Thank you for the feedback!  This is a great set of "mistakes", that I'd like the system to make less possible.  I'll work on thinking of how to avoid people "de-metadata-ing" the metadata.

About `ekg-rename-tag`, it appears that it isn't obvious this is for renaming all the instances of a tag, not a single tag in a single buffer.  I'll think of ways we can perhaps tweak the name to make it more obvious.

**Comment by ahyatt** [comment]
I've changed up how the metadata works in the `develop` branch in commit c1de20b74fbb6567fcc4e9fbb54af1e8cb85fbaa.  If you try it out, you should see that you can no longer just backspace over the overlay and destroy it.  I also changed it so that now there's a line saying "--text follows this line--", which is the same way `message-mode` works.  It should be more familiar and intuitive now, but please let me know if you try it.

**Comment by alecStewart1** [comment]
Thanks! I think this is a use-case for me to starting using [`vc-use-package`](https://github.com/slotThe/vc-use-package).

**Comment by alecStewart1** [comment]
What you added in commit `c1de20b` works. I tried using backspace, `C-S-e C-w`, `C-S-e C-d`, `C-d` multiple times, `C-k`, and backspacing and the overlay stays and I get a `This text is read-only` I remove text up to `Tag` (the semicolon I can remove).

**Comment by ahyatt** [comment]
I just submitted 71c06419fc126d30ef1cc0174af96b23f930ae45 in the `develop` branch, which renames `ekg-rename-tag` to `ekg-global-rename-tag`, which should be a better name.
