### ISSUE TITLE
transclue-note doesn't play well with text around

### ISSUE THREAD

**Issue by qingshuizheng** [ahyatt/ekg#41]
Hi @ahyatt , 

The transclude-* doesn't play quite well with text around. After `ekg-edit-finalize`, the transclude text will move one char forward. (Please note the "t" of "test"). 

Seems like a bug?

Original text:
![image](https://user-images.githubusercontent.com/78839107/235307159-800019b9-62f4-4c1d-b6b2-88c2f1f78779.png)

Run `C-c C-c` :
![image](https://user-images.githubusercontent.com/78839107/235305574-19338283-fe51-4acf-8aee-1c19c097a56a.png)

Open the note again:
![image](https://user-images.githubusercontent.com/78839107/235305677-89e9fd73-1988-49aa-a5ca-3c166d4ea595.png)

Zheng

Edit: update img

**Comment by ahyatt** [comment]
Thank you for your bug report, this should fix it!  I've also added a test so we can catch this in the future as well.

**Comment by qingshuizheng** [comment]
> Thank you for your bug report, this should fix it! I've also added a test so we can catch this in the future as well.

Thanks for the quick fix 👍 

There seems to be another issue: if %(transclude-* ) is inserted at last, the empty space b/t normal text and the transclude section will be swallowed.

Text:

![image](https://user-images.githubusercontent.com/78839107/235337494-feb22014-bbd4-4b5c-8f06-af57556a2dfa.png)

Run `C-c C-c` and re-open (only the last one is affected):

![image](https://user-images.githubusercontent.com/78839107/235337538-88543255-6dfb-4db1-91ce-98d336ac6be1.png)

**Comment by qingshuizheng** [comment]
> Thank you for your bug report, this should fix it! I've also added a test so we can catch this in the future as well.

Thanks for the quick fix. 👍 

There seems to be another issue: if %(transclude-* id) is inserted at last, the empty space b/t normal text and the transclude section will be swallowed (only the last one will be affected):

Text: 

![image](https://user-images.githubusercontent.com/78839107/235338007-4d8d3ef2-acb6-4cf0-9afb-97def8125671.png)

Run `C-c C-c` and re-open:

![image](https://user-images.githubusercontent.com/78839107/235338042-e5f41f80-9094-499c-a82c-e3492ffa1b28.png)

**Comment by ahyatt** [comment]
Interesting - I think that's because we trim text of whitespace on either side, which ordinarily is a good idea, but not with transclusions.

**Comment by qingshuizheng** [comment]
Now it works as expected. Thanks!
