### ISSUE TITLE
Double warning message

### ISSUE THREAD

**Issue by cuprum** [ahyatt/ekg#42]
![115](https://user-images.githubusercontent.com/532546/235527376-5706032b-ebc1-46fa-ac18-622ffd00bd5d.png)
When the cursor is after "Tit" as in the screenshot, I call completion-at-point (C-M-i).
After that completion happens and messages appears as follow:
![935](https://user-images.githubusercontent.com/532546/235527701-f86d2a1d-9bd9-462f-be40-dd40b3b423da.png)

It's very strange. I tested this on develop branch.
Win 10, Emacs 28.1.

**Comment by ahyatt** [comment]
Thank you for your bug report, I just checked in a fix!
