### ISSUE TITLE
Rename "Capture buffer" to "Edit buffer" in `ekg-edit-mode` header-line?

### ISSUE THREAD

**Issue by qingshuizheng** [ahyatt/ekg#44]
Hi @ahyatt 

https://github.com/ahyatt/ekg/blob/808921ab6eba83c7b943873265aecb8611dfa24a/ekg.el#LL902C43-L902C43

Since it's in `ekg-edit-mode`, would it be better to change "Capture buffer" to "Edit buffer" in header line, to reflect the correct minor mode? 😄 It's been nagging me for a while.

-----
From:
```
(substitute-command-keys
                   "\\<ekg-edit-mode-map>Capture buffer.  Finish \
`\\[ekg-edit-finalize]'.")
```
to

```
(substitute-command-keys
                   "\\<ekg-edit-mode-map>Edit buffer.  Finish \
`\\[ekg-edit-finalize]'.")
```

Zheng

Edited: add info.

**Comment by ahyatt** [comment]
Thanks for catching this mistake!  I fixed it, so it should be good now.
