### ISSUE TITLE
ekg stands for emacs knowledge graph. use it as its name

### ISSUE THREAD

**Issue by vonbecmann** [ahyatt/ekg#5]
emacs-knowledge-graph could be a better name.

**Comment by gnusupport** [comment]
I agree, but only if that is really so general, and if it is only note related, then it should not be named too general.

**Comment by ahyatt** [comment]
Yes, `ekg` seems like a neat name (it's the heartbeat of emacs!), and it does refer to a knowledge graph, but the acronym gives some plausible deniability :). Also, it's very short, which I like when naming and calling its functions.

But, I think this will grow beyond notes.  Already, it bookmarks URLs.  I'm hoping other people use the `triples` package as well to do similar things, but hopefully it's all one big graph.  If so, perhaps `ekg` is the most prominent part of that graph, if it is successful.
