### ISSUE TITLE
Logseq Export Warning About logseq/last-export property not found in schema

### ISSUE THREAD

**Issue by jayrajput** [ahyatt/ekg#62]
Running Ekg from main branch on my windows home laptop. Trying to export with `ekg-logseq-export` generates following error:

```
Property logseq/last-export not found in schema
```

This means that the exports are not incremental. Although export seems to work fine.

**Comment by jayrajput** [comment]
```
sqlite> SELECT * FROM triples WHERE subject LIKE '%logseq%';
subject   predicate        object  properties
--------  ---------------  ------  ----------
logseq    base/type        schema  (:t t)
logseq    schema/property  file    (:t t)
"logseq"  base/type        tag     (:t t)
```

The entries for `logseq/last-export` are missing. Looking more into it.

**Comment by jayrajput** [comment]
Explicitly calling `ekg-logseq-add-schema` fixed the problem

```
(defun ekg-logseq-add-schema ()
  "Add the logseq schema to the ekg database."
  (triples-add-schema ekg-db 'logseq
                      '(last-export :base/unique t :base/type integer)
                      '(last-import :base/unique t :base/type integer)))
```
I am running triples also from the main branch now.

**Comment by ahyatt** [comment]
The issue is that it won't add the schema until you reconnect to the database.  I need to figure out a good way to deal with this - it certainly isn't good that you had this experience.  I'm going to re-open this.
