### ISSUE TITLE
Error running ekg-embedding-show-similar for note with no text

### ISSUE THREAD

**Issue by jayrajput** [ahyatt/ekg#64]
I have some ekg notes with no content/text. They are generally pointing to a URL and I am using ekg notes to bookmark them. Since such notes has no text `substring-no-properties` generate the args-out-of-range error. Here is the error and the stack trace.

```
Debugger entered--Lisp error: (args-out-of-range "" 0 10)
  substring-no-properties("" 0 10)
  (format "%s..." (substring-no-properties ...
  ekg-note-snippet(....)
```

**Comment by ahyatt** [comment]
Thank you for reporting this!
