### ISSUE TITLE
Error with (ekg-org-roam-import)

### ISSUE THREAD

**Issue by RazikSF** [ahyatt/ekg#7]
Hi,

I'm getting the following error when calling `ekg-org-roam`:

```emacs-lisp
Debugger entered--Lisp error: (void-function string-equal-ignore-case)
```

**Comment by RazikSF** [comment]
Sometiems I get this error instead:

```emacs-lisp
Debugger entered--Lisp error: (void-function ekg--connect)
  (ekg--connect)
  ekg-org-roam-import()
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  eros-eval-last-sexp(nil)
  funcall-interactively(eros-eval-last-sexp nil)
  command-execute(eros-eval-last-sexp)
```

**Comment by ahyatt** [comment]
Thanks... for the first one, that's odd and I'll look into it.  What version of emacs are you running?

For the second one, that seems like it would happen if you haven't loaded the `ekg` library, which should have happened by this point.  I'll think about it, thank you for the report.

**Comment by RazikSF** [comment]
I'm running emacs 28.2 with doom.

When I load the `ekg` library manually, I don't get the second error anymore.

**Comment by ahyatt** [comment]
Evidently `string-equal-ignore-case` is new in emacs 29.1, so I'll find a substitute.

**Comment by RazikSF** [comment]
Thank you! Works perfectly now.
