### ISSUE TITLE
Cannot Delete Old Notes with Integer Content

### ISSUE THREAD

**Issue by jayrajput** [ahyatt/ekg#70]
I have some old notes which contains only integer values. I was storing the saving interest credited to my account. I cannot delete/view them. When trying to view them emacs, show them as foreign characters rather than integers. Trying to delete also fails. I can see them in the database

```
sqlite> SELECT * FROM triples where object LIKE '%340';
33680749501|text/text|340|(:t t)
sqlite> SELECT * FROM triples where object LIKE '%486';
33680744133|text/text|486|(:t t)
```

Btw, any new notes created with just integer value is saved as string and can be viewed/deleted fine. The problem is with the old notes.

**Comment by ahyatt** [comment]
Did you run the latest upgrade code, checked in with commit c216cf92b3536bd204aa242054e5d1e907c9dc78?   It has a fix for this, and it should have run, upgrading all these value back to strings.  If you haven't been using that commit or later, please try it and it should fix this (if you are running in emacs 29, using the builtin sqlite).

**Comment by jayrajput** [comment]
I can see I am already at 0.3.1, which explains that the new upgrade code did not ran. Output of  `(pp (plist-get ekg-plist :version))` is `(0 3 1)` for me.  So I tried to hack the code and force execute the upgrade code, but that did not helped. Eventually tracked done that the this SQL query is not working.

```
UPDATE OR IGNORE triples SET object = CAST(object AS TEXT) WHERE predicate = 'text/text' AND typeof(object) = 'integer'
```

The query expects the type of object column as integer. But I can see the type as text'. Here is some sample rows which are creating problem for me

```
sqlite> SELECT * FROM triples where object LIKE '%340';
33680749501|text/text|340|(:t t)
33657705192|text/text|340|()
sqlite> SELECT typeof(object) FROM triples where object LIKE '%340';
text
text
```

**Comment by jayrajput** [comment]
Also here is my schema. Object column is not text as done for other columns. Not sure if that makes a difference:

```
sqlite> .schema
CREATE TABLE triples (subject NOT NULL, predicate text NOT NULL, object NOT NULL, properties text NOT NULL);
CREATE INDEX subject_idx ON triples (subject);
CREATE INDEX subject_predicate_idx ON triples (subject, predicate);
CREATE INDEX predicate_object_idx ON triples (predicate, object);
CREATE UNIQUE INDEX subject_predicate_object_properties_idx ON triples (subject, predicate, object, properties);
```

**Comment by ahyatt** [comment]
Thanks for the thorough report, this highlights an error in my previous update code.  I've reproduced your issue and checked in 36a8d2d67e381eda6acdeebbbc517c2aee88085c which should fix it. 

If you execute `delete from triples where subject = "ekg";` in your sqlite database, and try the update again, it should succeed now.  Thanks for the patience with this fix.

**Comment by jayrajput** [comment]
Ok. Away from home laptop now. I will try and let you know in another 12
hour.

**Comment by jayrajput** [comment]
This did not worked. I did deleted ekg entries form the triples db. The string "Upgraded all stringified integers in triple database to actual integers" can be seen in the messages indicating that the upgrade code did got executed.  I did ran the modified SQL on my system, but that did not returned the bad rows as the `typeof` return `text` and not `integer`. Here are multiple SQL output:

```
sqlite> SELECT COUNT(*) FROM triples WHERE predicate = 'text/text' AND typeof(object) = 'integer';
0
sqlite> SELECT * FROM triples where object LIKE '%340';
33680749501|text/text|340|(:t t)
33657705192|text/text|340|()
sqlite> SELECT typeof(object) FROM triples where object LIKE '%340';
text
text
sqlite>
```

**Comment by jayrajput** [comment]
What about updating the SQL to use REGEXP. Something like this

```
sqlite> SELECT * FROM triples WHERE predicate = 'text/text' AND object REGEXP '^[0-9]+$';
33680749501|text/text|340|(:t t)
33657705192|text/text|340|()
33680744133|text/text|486|(:t t)
```

**Comment by ahyatt** [comment]
Apologies, I neglected to mention one key point: you had to downgrade back to integers first (because of my error, we botched the initial upgrade), can you first try this, and then upgrade again?  

```
UPDATE OR IGNORE triples SET object = CAST(object) as INTEGER WHERE predicate = 'text/text' and object REGEXP '^[0-9]+$';
```

**Comment by jayrajput** [comment]
Yes. This is working now. SQL queries had minor typos which I had to fix.

**Comment by ahyatt** [comment]
Thanks!  I just realized I had another issue as well that I need to fix in the upgrade code.  But thanks to your help, I think we've got almost all of them.
