### ISSUE TITLE
Could not find package `triples.el`

### ISSUE THREAD

**Issue by CGenie** [ahyatt/ekg#8]
I'm getting this error when trying the setup instructions from the README:
```
Debugger entered--Lisp error: (error "Could not find package triples\\.el. Updating recip...")
  error("Could not find package %S. Updating recipe reposit..." triples\.el (org-elpa melpa gnu-elpa-mirror nongnu-elpa el-get emacsmirror-mirror))
```
I think it's because of this line https://github.com/ahyatt/ekg/blob/main/ekg.el#L7. For triples we have `(provide triples)` not `(provide triples.el)`: https://github.com/ahyatt/triples/blob/main/triples.el#L628

**Comment by ahyatt** [comment]
Thanks, I think your diagnosis is correct.  I'll push a fix now.
