### ISSUE TITLE
byte compiling warnings/error + native compiling warnings/error

### ISSUE THREAD

**Issue by rbenit68** [ahyatt/ekg#87]
Hi,

Trying a fresh install of ekg, I start Emacs 29.1 Mac (with-native-comp) with **no .emacs.d directory** and with **.emacs** file with this minimal content

```
(require 'package)
;;(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)

(use-package ekg
   :ensure t)
```

I get the following warnings and errors

```
Warning (bytecomp): the function ‘kvplist->alist’ is not known to be defined.
Warning (bytecomp): the function ‘kvalist-sort’ is not known to be defined.
Warning (bytecomp): the function ‘kvalist->plist’ is not known to be defined.
Warning (bytecomp): Unused lexical argument `db'
Warning (bytecomp): reference to free variable ‘emacsql-sqlite-executable’
Warning (bytecomp): the function ‘emacsql-with-transaction’ is not known to be defined.
Warning (bytecomp): the function ‘emacsql-close’ is not known to be defined.
Warning (bytecomp): the function ‘emacsql’ is not known to be defined.
Warning (bytecomp): the function ‘emacsql-sqlite’ is not known to be defined.
Error (bytecomp): Cannot open load file: No such file or directory, request
```

```
⛔ Warning (comp): triples.el:138:24: Warning: Unused lexical argument `db'
⛔ Warning (comp): triples.el:157:31: Warning: reference to free variable `emacsql-sqlite-executable'
⛔ Warning (comp): triples.el:521:11: Warning: macro `triples-with-transaction' defined too late
⛔ Warning (comp): triples.el:400:7: Warning: the function `emacsql-with-transaction' is not known to be defined.
⛔ Warning (comp): triples.el:136:16: Warning: the function `emacsql-close' is not known to be defined.
⛔ Warning (comp): triples.el:108:17: Warning: the function `emacsql' is not known to be defined.
⛔ Warning (comp): triples.el:106:20: Warning: the function `emacsql-sqlite' is not known to be defined.
⛔ Warning (comp): /Users/user00/.emacs.d/elpa/ekg-0.3.2/ekg.el: Error: Invalid function #<subr or>
```

And no ekg.eln native compiled file.

If I call ekg-capture (without restarting Emacs), I get

```
triples-rebuild-builtin-database: Invalid function: triples-with-transaction
```

I restart Emacs, I get

```
⛔ Warning (comp): /Users/rbenit68/.emacs.d/elpa/ekg-0.3.2/ekg.el: Error: Invalid function #<subr or>
```

I call ekg-capture, I get

```
Invalid function: triples-with-transaction
```

I delete in turn ekg*.elc, triples*.eln, and triples.elc

I can use ekg only when triples*.eln, triples*.elc and ekg.elc are deleted.

Thank you for ekg!

**Comment by ahyatt** [comment]
I don't really know about native compilation, and I've never been able to get an emacs with it compiled in, so I can't try to reproduce those problems.

I checked in a changes to the `develop` branch on triples that should fix some of your problems.

I haven't been able to reproduce any issue with an invalid function `or`.  

As far as the issues with `kvplist`, those are for the testing class, which requires a library that isn't in the package dependencies.  I don't want to include testing-only packages in the package depends.  Hopefully these are just warnings and nothing will break.  A similar thing exists for `request`, which is for `ekg-embedding`, which, if you don't use, you don't need.  I should document that, though.

Please try the new triples changes and see if that fixes the actual functionality breakages.

**Comment by rbenit68** [comment]
Thank you for your reply.

I have tried the new triples changes and all the warnings have disappeared, thank you.

I have isolated (brute force) the code that is blocking the native compiling:

```
(defun ekg-change-mode (mode)
  "Change the mode to MODE of the current note."
  (interactive (list (completing-read "Mode: " ekg-acceptable-modes))
               ekg-capture-mode ekg-edit-mode)
  (let ((minor-mode (if ekg-capture-mode "capture" "edit"))
        (note ekg-note))
    (funcall (intern mode))
    (funcall (intern (format "ekg-%s-mode" minor-mode)))
    (setq header-line-format
          (substitute-command-keys
           (format "\\<ekg-%s-mode-map>%s buffer.  Finish \
`\\[ekg-%s-finalize]'." minor-mode (capitalize minor-mode) minor-mode)))
    (setq ekg-note note)))
```

Just by changing ```(capitalize minor-mode)``` for ``` minor-mode ``` I get no errors, but a warning

 ```ekg.el:951:37: Warning: the function ‘minor-mode’ is not known to be defined.```

I cannot figure out the reason. I suppose that you will be clearer about the definition of functions and variables than me.

Best.

**Comment by ahyatt** [comment]
I've pushed a new version of ekg that should fix the issue you are reporting (at least the native-comp one).  Very mysterious, I can't imagine what is going wrong here.  I hope this new version resolves all your problems, if not please do re-open this.
