### ISSUE TITLE
Make the metadata separator configurable

### ISSUE THREAD

**Issue by Gleek** [ahyatt/ekg#90]
Hello,
I'd like to use a different separator between the metadata and the text from the more practical but arguably less eye pleasing `--text follows this line--` to something like a proper line separator. Doing this right now from outside the package is quite cumbersome. I'd request that this string be extracted out as a `defvar` that can be edited by the user, so the process becomes easier. I'd suggest the following change and can raise a pull request if you're open to it.

```diff
@@ -161,6 +161,9 @@
   "Alist of properties that can be on the note and their labels.
 The label needs to match the keys in the `ekg-metadata-parsers' alist.")
 
+(defvar ekg-metadata-separator-text "--text follows this line--"
+  "Separator between the metadata of the note and the note text")
+
 (defvar ekg-add-schema-hook nil
   "Hook run when ensuring schema for ekg.
 This is run on connection. Calls to `triples-add-schema' are
@@ -893,7 +896,7 @@
     (goto-char (overlay-end o))
     (insert "\n")
     (move-overlay o (point-min) (- (overlay-end o) 1))
-    (overlay-put o 'after-string (propertize "--text follows this line--\n"
+    (overlay-put o 'after-string (propertize (concat ekg-metadata-separator-text "\n")
                                              'read-only t 'rear-nonsticky t))
     (overlay-put o 'category 'ekg-metadata)
     (overlay-put o 'modification-hooks '(ekg--metadata-modification))
```

PS: In my config I use a group of "━" characters to create the visual effect of the line. I plan to later calculate the number of such characters based on the window width as is done in org agenda.

Regards.

**Comment by ahyatt** [comment]
This seems like a good idea, thank you!  Could you open a pull request, and implement it as a defcustom?

**Comment by ahyatt** [comment]
Your fix has now been merged into the develop branch, so I'm closing this.  Thank you for the report and fix!
