### ISSUE TITLE
feature: Take notes on codebase.

### ISSUE THREAD

**Issue by mohammedzeglam-pg** [ahyatt/ekg#93]
I started use ekg from 2 days, it is awesome to make notes as you read feeds articles books.
But in my mind it will take a boost to make notes on codebase and as you read codebase and understand what the component of the system and you jump between modules you could read all notes about system or read specific note it will boost as you work on os project or a freelancer need to change on  system but need a map on some component how it works.

This just feature request and I am in love with this project and it is really workflow boost.

**Comment by ahyatt** [comment]
That's quite interesting, and I think it's not too hard to do.  Let me experiment with a few things to see if it's as easy as I think it is.

**Comment by ahyatt** [comment]
Please take a look at `develop` branch, which now has `ekg-capture-file`.  Call it once on any file to create a note about that file, and call it again to open that note.  I tried it and it seems pretty nice and useful, thanks for suggesting this!  Let me know if there's anything that can be improved upon.

**Comment by mohammedzeglam-pg** [comment]
> Please take a look at `develop` branch, which now has `ekg-capture-file`. Call it once on any file to create a note about that file, and call it again to open that note. I tried it and it seems pretty nice and useful, thanks for suggesting this! Let me know if there's anything that can be improved upon.

for me it seems perfect i think it is even work with pdfs epub and other this mean you could take notes for the same if you study some book for exam.

maybe one other feature for codebases just ekg-follow like treemacs i thing have follow feature i do not use treemacs but maybe this will be hard.

and thanks
